name = "Opencomputers Pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e90d52cbbbee734396965c9a1159fafb7179e6db0533d901d238e1533772281"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"
