name = "Opencomputers Pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0dbd0103829129a4ad20afea673dfab0767f222da426c00ebd75346746a3243"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"
